let Input = document.getElementById("InputOne");
let Output1 = document.getElementById("Output1");
let Output2 = document.getElementById("Output2");
let Output3 = document.getElementById("Output3");
let Output4 = document.getElementById("Output4");
let Output5 = document.getElementById("Output5");
let Output6 = document.getElementById("Output6");
let Output7 = document.getElementById("Output7");
let Output8 = document.getElementById("Output8");
let Output9 = document.getElementById("Output9");
let Output10 = document.getElementById("Output10");
let Output11 = document.getElementById("Output11");
let Output12 = document.getElementById("Output12");
let Output13 = document.getElementById("Output13");
let Output14 = document.getElementById("Output14");
let Output15 = document.getElementById("Output15");
let Output16 = document.getElementById("Output16");
let Output17 = document.getElementById("Output17");
let Output18 = document.getElementById("Output18");
let Output19 = document.getElementById("Output19");
function SetOutput1() {
    Output1.innerHTML = document.getElementById("InputOne").value;
    alert(document.getElementById("InputOne").value);
}
function SetOutput2() {
    Output2.innerHTML = document.getElementById("InputOne").value;
    alert(document.getElementById("InputOne").value);
}
function SetOutput3() {
    Output3.innerHTML = document.getElementById("InputOne").value;
    alert(document.getElementById("InputOne").value);
}
function SetOutput4() {
    Output4.innerHTML = document.getElementById("InputOne").value;
    alert(document.getElementById("InputOne").value);
}
function SetOutput5() {
    Output5.innerHTML = document.getElementById("InputOne").value;
    alert(document.getElementById("InputOne").value);
}
function SetOutput6() {
    Output6.innerHTML = document.getElementById("InputOne").value;
    alert(document.getElementById("InputOne").value);
}
function SetOutput7() {
    Output7.innerHTML = document.getElementById("InputOne").value;
    alert(document.getElementById("InputOne").value);
}
function SetOutput8() {
    Output8.innerHTML = document.getElementById("InputOne").value;
    alert(document.getElementById("InputOne").value);
}
function SetOutput9() {
    Output9.innerHTML = document.getElementById("InputOne").value;
    alert(document.getElementById("InputOne").value);
}
function SetOutput10() {
    Output10.innerHTML = document.getElementById("InputOne").value;
    alert(document.getElementById("InputOne").value);
}
function SetOutput11() {
    Output11.innerHTML = document.getElementById("InputOne").value;
    alert(document.getElementById("InputOne").value);
}
function SetOutput12() {
    Output12.innerHTML = document.getElementById("InputOne").value;
    alert(document.getElementById("InputOne").value);
}
function SetOutput13() {
    Output13.innerHTML = document.getElementById("InputOne").value;
    alert(document.getElementById("InputOne").value);
}
function SetOutput14() {
    Output14.innerHTML = document.getElementById("InputOne").value;
    alert(document.getElementById("InputOne").value);
}
function SetOutput15() {
    Output15.innerHTML = document.getElementById("InputOne").value;
    alert(document.getElementById("InputOne").value);
}
function SetOutput16() {
    Output16.innerHTML = document.getElementById("InputOne").value;
    alert(document.getElementById("InputOne").value);
}
function SetOutput17() {
    Output17.innerHTML = document.getElementById("InputOne").value;
    alert(document.getElementById("InputOne").value);
}
function SetOutput18() {
    Output18.innerHTML = document.getElementById("InputOne").value;
    alert(document.getElementById("InputOne").value);
}
function SetOutput19() {
    Output19.innerHTML = document.getElementById("InputOne").value;
    alert(document.getElementById("InputOne").value);
}
function EraseOutput1() {
    Output1.innerHTML = "Finished";
    alert("Erase/Complete task");
}
function EraseOutput2() {
    Output2.innerHTML = "Finished";
    alert("Erase/Complete task");
}
function EraseOutput3() {
    Output3.innerHTML = "Finished";
    alert("Erase/Complete task");
}
function EraseOutput4() {
    Output4.innerHTML = "Finished";
    alert("Erase/Complete task");
}
function EraseOutput5() {
    Output5.innerHTML = "Finished";
    alert("Erase/Complete task");
}
function EraseOutput6() {
    Output6.innerHTML = "Finished";
    alert("Erase/Complete task");
}
function EraseOutput7() {
    Output7.innerHTML = "Finished";
    alert("Erase/Complete task");
}
function EraseOutput8() {
    Output8.innerHTML = "Finished";
    alert("Erase/Complete task");
}
function EraseOutput9() {
    Output9.innerHTML = "Finished";
    alert("Erase/Complete task");
}
function EraseOutput10() {
    Output10.innerHTML = "Finished";
    alert("Erase/Complete task");
}
function EraseOutput11() {
    Output11.innerHTML = "Finished";
    alert("Erase/Complete task");
}
function EraseOutput12() {
    Output12.innerHTML = "Finished";
    alert("Erase/Complete task");
}
function EraseOutput13() {
    Output13.innerHTML = "Finished";
    alert("Erase/Complete task");
}
function EraseOutput14() {
    Output14.innerHTML = "Finished";
    alert("Erase/Complete task");
}
function EraseOutput15() {
    Output15.innerHTML = "Finished";
    alert("Erase/Complete task");
}
function EraseOutput16() {
    Output16.innerHTML = "Finished";
    alert("Erase/Complete task");
}
function EraseOutput17() {
    Output17.innerHTML = "Finished";
    alert("Erase/Complete task");
}
function EraseOutput18() {
    Output18.innerHTML = "Finished";
    alert("Erase/Complete task");
}
function EraseOutput19() {
    Output19.innerHTML = "Finished";
    alert("Erase/Complete task");
}
let SortNum = 0;
let OldNum;
let DeleteNum;
let AllNum;
function Sortemall() {
    SortNum += 1
    alert(SortNum)
    if (SortNum == 1 )  {
        SetOutput1()
    }
    if (SortNum == 2 )  {
        SetOutput2()
    }
    if (SortNum == 3 )  {
        SetOutput3()
    }
    if (SortNum == 4 )  {
        SetOutput4()
    }
    if (SortNum == 5 )  {
        SetOutput5()
    }
    if (SortNum == 6 )  {
        SetOutput6()
    }
    if (SortNum == 7 )  {
        SetOutput7()
    }
    if (SortNum == 8 )  {
        SetOutput8()
    }
    if (SortNum == 9 )  {
        SetOutput9()
    }
    if (SortNum == 10 )  {
        SetOutput10()
    }
    if (SortNum == 11)  {
        SetOutput11()
    }
    if (SortNum == 12)  {
        SetOutput12()
    }
    if (SortNum == 13)  {
        SetOutput13()
    }
    if (SortNum ==14)  {
        SetOutput14()
    }
    if (SortNum == 15)  {
        SetOutput15()
    }
    if (SortNum ==16)  {
        SetOutput16()
    }
    if (SortNum ==17)  {
        SetOutput17()
    }
    if (SortNum == 18)  {
        SetOutput18()
    }
    if (SortNum ==19)  {
        SetOutput19()
    }
}
function Deleteemall() {

}
function deletesortemall() {
    
}
